FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libcairo2-dev libxcb-image0-dev

ADD . /repo
WORKDIR /repo
RUN ./build-example-with-cairo.sh
