FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libcairo2-dev libxcb-image0-dev

COPY . /repo
WORKDIR /repo
RUN ./build-example-with-cairo.sh

FROM ubuntu:20.04 as package
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libcairo2-dev
COPY --from=builder /repo/gen/bin/iconvg-to-png-with-cairo /
